### ISSUE TITLE
Element find

### ISSUE THREAD

**Issue by somebody1234** [minxomat/zQuery#3]
Instead of `[...myMultipleElements].map(x => [...x.querySelectorAll('.foo')]).reduce((a, b) => [...a, ...b]);`, I think `[].concat.apply([], [...myMultipleElements].map(x => [...x.querySelectorAll('.foo')]));` should be faster.

**Comment by vihanb** [comment]
Bind operator is good use here:

``` js
let { forEach, map } = [];

document.querySelectorAll("*")::forEach(el => el)
```
